### ISSUE TITLE
Dependency/Ordering mayhem

### ISSUE THREAD

**Issue by zslabs** [ismay/metalsmith-in-place#136]
I believe this might be more of an issue than a support request (but obviously comes with a request; or cry for help depending on how you look at it)

👋

We've been using an older version of metalsmith-in-place and metalsmith-layouts for quite some time. Recently, with the update to jstransformers in metalsmith-layouts I decided to give transferring [my setup](https://github.com/rhinogram/rhinostyle/blob/rg3Develop/config/pages.js#L47) to the newer versions. While I do have Nunjucks compiling correctly with the options I need, getting the order of Metalsmith plugins to play nicely has been very frustrating.

I think the kicker is the jstransformer dictionary is looking for Nunjucks files to either have .nunjucks or .njk extension, which "I believe" has caused the metalsmith-permalinks plugin to not work correctly since it's not a HTML file at this point. I also need the metalsmith-rootpath plugin to happen before transformation, which ultimately has lead me into a circular dependency nightmare.

Any thoughts on where I'm going wrong with this? I know support for some of these plugins has been sparse, but I don't think it should be this difficult to upgrade.

Hopefully an easier request -- is there a way to force jstransformer to recognize a certain file extension as another? So that .html is recognized and run through jstransformer-nunjucks?

**Comment by ismay** [comment]
Hi @zslabs. Hmm. If the older versions of this plugin and layouts worked better for you, why not keep using them? There’s nothing wrong with them, so might be the easiest solution 🙂

But if you want to use the newest versions, then I think your quickest solution is to ask this question in the slack channel. A lot of plugin developers hang out there. That being said, I wouldn’t mind taking a look at this, but I’ll need a repo with a demonstration of the problem.

I’ll close this because I don’t yet see the bug or any concrete malfunctioning of the plugin, but feel free to correct me.

**Comment by zslabs** [comment]
Hey @ismay,
Thanks for the quick response! I have this one on [stackoverflow](https://stackoverflow.com/questions/48269489/metalsmith-jstransformer-and-ordering-mayhem) as well, but the Slack channel may not be a bad idea. I'm honestly 100% okay with keeping the older versions going, but figured they may not be updated in the future with any API changes that could come into play with Metalsmith. Just didn't want to get too far behind on that one. Thanks again!

**Comment by zslabs** [comment]
In the event you are interested in taking a look, I've pushed https://github.com/rhinogram/rhinostyle/tree/zach/metalsmith-test up and you can see the diff at https://github.com/rhinogram/rhinostyle/compare/zach/metalsmith-test?expand=1 Basically the permalinks plugin doesn't appear to be picking up the `.njk` files, but that's needed for the jstransformers.

**Comment by ismay** [comment]
> but figured they may not be updated in the future with any API changes that could come into play with Metalsmith. Just didn't want to get too far behind on that one.

Yeah I understand

So I took a quick look. The diff you linked was a bit much, since it includes the build folder and it choked my browser a bit, so I mainly looked at the build script:

```javascript
// rhinostyle/config/pages.js
export default function pages() {
  return metalsmith(process.cwd())
    .source('./src')
    .clean(false)
    .use(msIgnore(ignoreDirectories))
    .use(msPermalinks())
    .use(msMoveUp({
      pattern: 'pages/**/*',
    }))
    .use(msRootpath())
    .use(msInPlace({
      engineOptions: {
        cache: false,
      },
    }))
    .use(msLayouts({
      directory: './src/templates',
      default:   'default.njk',
      engineOptions: {
        cache: false,
      },
    }))
    .destination('./build')
    .build((err) => {
      if (err) {
        throw err;
      } else {
        reload();
      }
    });
```

So with the rootpath plugin, you're using it like so:

```nunjucks
<img class="rhino-animation__time" src="{{rootPath}}animation/time/sprite.svg" alt="" />
```

Why not remove the rootPath plugin and do:

```nunjucks
// See https://webmasters.stackexchange.com/a/56844
<img class="rhino-animation__time" src="/animation/time/sprite.svg" alt="" />
```

Then you can run inplace and layouts first, and permalinks and moveup afterwards:

```javascript
    .use(msInPlace({
      engineOptions: {
        cache: false,
      },
    }))
    .use(msLayouts({
      directory: './src/templates',
      default:   'default.njk',
      engineOptions: {
        cache: false,
      },
    }))
    .use(msPermalinks())
    .use(msMoveUp({
      pattern: 'pages/**/*',
    }))
```

Does that solve the problem?

**Comment by zslabs** [comment]
Hey, so the main problem with removing `rootPath` is on sites that run in a subfolder, like that repos documentation site. If you visit https://rhinogram.github.io/rhinostyle/ you'll notice the URLs need to be constructed in a manner that can always relate back to the root based on how GitHub pages are created.

**Comment by ismay** [comment]
Ok, so if you want to reference something relative to the root of the site then that should solve it:

```html
<!— note the preceding slash in src —>
<img class="rhino-animation__time" src="/rhinostyle/animation/time/sprite.svg" alt="" />
```

When deployed on `https://rhinogram.github.io/` that `src=` would always be resolved by the browser as `https://rhinogram.github.io/rhinostyle/animation/time/sprite.svg`, no matter how deep the page is nested. Which is due to the preceding slash, making it an absolute link that refers to the root.

I might be stating the obvious, or misunderstanding your usecase, but that seems like a solution to me.

**Comment by zslabs** [comment]
Appreciate with you sticking with me on this one ;) Ha yeah a bit obvious, but it was more about not having to think about the end-path of where something is deployed, more just how far up the relative tree the base is. I may work on something that just feeds through a root path var to all of my templates though instead just since this may be one of the only things holding me back. Thanks for your help with this!

**Comment by ismay** [comment]
> it was more about not having to think about the end-path of where something is deployed

I understand, it just seems like imposing that constraint on yourself is now causing some difficulties in your build process :)

But you could also solve it in your templating, should also be able to address this. Happy to help! 👍
